FROM openjdk:17-jdk-slim
ARG SERVER_PORT
ENV SERVER_PORT=$SERVER_PORT
ARG DB_URL
ENV DB_URL=$DB_URL
ARG DB_PORT
ENV DB_PORT=$DB_PORT
ARG DB_NAME
ENV DB_NAME=$DB_NAME
ARG DB_USER
ENV DB_USER=$DB_USER
ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD
ARG COGNITO_CLIENT_ID
ENV COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
ARG COGNITO_CLIENT_SECRET
ENV COGNITO_CLIENT_SECRET=$COGNITO_CLIENT_SECRET
ARG COGNITO_REDIRECT_URL
ENV COGNITO_REDIRECT_URL=$COGNITO_REDIRECT_URL
ARG COGNITO_REDIRECT_URL_PORT
ENV COGNITO_REDIRECT_URL_PORT=$COGNITO_REDIRECT_URL_PORT
ARG COGNITO_CLIENT_NAME
ENV COGNITO_CLIENT_NAME=$COGNITO_CLIENT_NAME
ARG AWS_REGION
ENV AWS_REGION=$AWS_REGION
ARG COGNITO_USER_POOL_ID
ENV COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID

COPY . ./app

WORKDIR ./app
RUN chmod +x gradlew && ./gradlew build
WORKDIR ./build/libs/
ENTRYPOINT ["java", "-jar", "aws-auth-0.0.1-SNAPSHOT-plain.jar"]