server:
  port: ${SERVER_PORT}
  servlet:
    context-path: "/api/v1"
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid
            redirect-uri: ${COGNITO_REDIRECT_URL}:${COGNITO_REDIRECT_URL_PORT}/login/oauth2/code/cognito
            clientName: ${COGNITO_CLIENT_NAME}
        provider:
          cognito:
            issuerUri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
            user-name-attribute: phone_number
