server:
  port: 8081
  servlet:
    context-path: "/api/v1"
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/redb
    username: "reuser"
    password: "1q2w3e"
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 43ga2vh2k6jja9iaa9td48jf35
            clientSecret: 16439qeea9g54bbe1fkfnrilpa4d74eb1bkl6usn4qocn890ffie
            scope: openid
            redirect-uri: http://localhost:8081/login/oauth2/code/cognito
            clientName: aws-auth-app
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_9HRiNN85M
            user-name-attribute: phone_number
