server:
  port: ${SERVER_PORT}
spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid
            redirect-uri: ${COGNITO_REDIRECT_URL}:${COGNITO_REDIRECT_URL_PORT}/login/oauth2/code/cognito
            clientName: ${COGNITO_CLIENT_NAME}
        provider:
          cognito:
            issuerUri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
            user-name-attribute: phone_number
